name: apache-generic

services:
  apache:
    container_name: apache
    image: php:apache
    # environment:
    #   - name=value
    restart: unless-stopped
    ports:
      - '${APACHE_PORT}:80'
    networks:
      - apache_net
    volumes:
      - web_data:/var/www/html
      - web_crs:/etc/apache2/
      - web_log:/var/log/apache2
      - web_lib:/usr/lib/
      - web_security:/etc/modsecurity/
    configs:
      - source: secure-apache-conf
        target: /etc/apache2/apache2.conf
      - source: secure-php-conf
        target: /usr/local/etc/php/php.ini
    depends_on:
      - mysql
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: unless-stopped
    ports:
      - '${PHPMYADMIN_PORT}:80'
    networks:
      - pma_net
    depends_on:
      - mysql
  
  mysql:
    container_name: presta_db
    image: mysql:5.5
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: ${PRESTA_DB_PASSWD}
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASSWD}
    restart: unless-stopped
    networks:
      - apache_net
      - pma_net
    volumes:
      - db_data:/var/lib/mysql

networks:
  apache_net:
  pma_net:

volumes:
  db_data:
  web_data:
  web_crs:
  web_security:
  web_log:
  web_lib:

configs:
  secure-apache-conf:
    file: ./apache2.conf
  secure-php-conf:
    file: ./php.ini
